/*
 * Copyright 2016-2026 The NATS Authors
 * Licensed under the Apache License, Version 2.0 (the "License");
 * you may not use this file except in compliance with the License.
 * You may obtain a copy of the License at
 *
 * http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS,
 * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 * See the License for the specific language governing permissions and
 * limitations under the License.
 */

"use strict";

const digits = "0123456789ABCDEFGHIJKLMNOPQRSTUVWXYZabcdefghijklmnopqrstuvwxyz";
const base = 62;
const preLen = 12;
const seqLen = 10;
const minInc = 33;
const maxInc = 333;
const totalLen = preLen + seqLen;

// Precomputed digit char codes — avoids repeated `digits.charCodeAt(i)`
// in the per-call hot path (`fillSeq` runs 10 lookups per `next()`).
const DIGIT_CODES = new Uint8Array(base);
for (let i = 0; i < base; i++) DIGIT_CODES[i] = digits.charCodeAt(i);

// base^seqLen exceeds Number.MAX_SAFE_INTEGER, so seq is stored as two 32-bit
// halves: seq = seqHi * 2^32 + seqLo. Boundaries derived via BigInt to avoid
// double-precision rounding traps in the literal/intermediate math.
const TWO32 = 0x1_0000_0000;
const _MAX_SEQ = BigInt(base) ** BigInt(seqLen);
const MAX_HI = Number(_MAX_SEQ / (1n << 32n));
const MAX_LO = Number(_MAX_SEQ % (1n << 32n));

function _getRandomValues(a: Uint8Array) {
  for (let i = 0; i < a.length; i++) {
    a[i] = Math.floor(Math.random() * 255);
  }
}

function fillRandom(a: Uint8Array) {
  if (globalThis?.crypto?.getRandomValues) {
    globalThis.crypto.getRandomValues(a);
  } else {
    _getRandomValues(a);
  }
}

/**
 * Nuid is a class that generates unique identifiers.
 *
 * Each id is 22 base-62 characters (alphabet `0-9A-Za-z`):
 *   12-char crypto-random prefix + 10-char base-62 sequence.
 *
 * Output format matches Go `nats-io/nuid` — same alphabet and length —
 * so nuids generated here look the same as nuids generated by Go.
 */
export class Nuid {
  /**
   *   @hidden
   */
  buf: Uint8Array;
  /**
   *   @hidden
   */
  private cbuf: Uint8Array;
  /**
   * Upper 32 bits of the sequence counter.
   * @hidden
   */
  seqHi!: number;
  /**
   * Lower 32 bits of the sequence counter.
   * @hidden
   */
  seqLo!: number;
  /**
   * @hidden
   */
  inc!: number;
  /**
   * @hidden
   */
  inited: boolean;

  constructor() {
    this.buf = new Uint8Array(totalLen);
    this.cbuf = new Uint8Array(preLen);
    this.inited = false;
  }

  /**
   * Initializes a nuid with a crypto random prefix,
   * and pseudo-random sequence and increment. This function
   * is only called if any api on a nuid is called.
   *
   * @ignore
   */
  private init() {
    this.inited = true;
    this.setPre();
    this.initSeqAndInc();
    this.fillSeq();
  }

  /**
   * Initializes the pseudo random sequence number and the increment range.
   * @ignore
   */
  private initSeqAndInc() {
    // r may be < 2^53 with a fractional part — both halves must be floored
    // so fillSeq's DIGIT_CODES index stays integral.
    const r = Math.random() * 839299365868340224;
    this.seqHi = Math.floor(r / TWO32);
    this.seqLo = Math.floor(r - this.seqHi * TWO32);
    this.inc = (Math.random() * (maxInc - minInc) + minInc) | 0;
  }

  /**
   * Sets the prefix from crypto random bytes. Converts them to base62.
   *
   * @ignore
   */
  private setPre() {
    fillRandom(this.cbuf);
    for (let i = 0; i < preLen; i++) {
      this.buf[i] = DIGIT_CODES[this.cbuf[i] % base];
    }
  }

  /**
   * Fills the sequence portion of the buffer as base62 from
   * the split-int seq (seqHi, seqLo). Performs long division
   * by 62 over the 64-bit value using doubles only — no bigint.
   *
   * @ignore
   */
  private fillSeq() {
    let hi = this.seqHi;
    let lo = this.seqLo;
    for (let i = totalLen - 1; i >= preLen; i--) {
      const hiQ = Math.floor(hi / base);
      const hiR = hi - hiQ * base;
      // combined <= 61 * 2^32 + (2^32-1) < 2^53 — exact in double
      const combined = hiR * TWO32 + lo;
      const loQ = Math.floor(combined / base);
      const rem = combined - loQ * base;
      this.buf[i] = DIGIT_CODES[rem];
      hi = hiQ;
      lo = loQ;
    }
  }

  /**
   * Returns the next nuid.
   */
  next(): string {
    if (!this.inited) {
      this.init();
    }
    this.seqLo += this.inc;
    if (this.seqLo >= TWO32) {
      this.seqLo -= TWO32;
      this.seqHi += 1;
    }
    if (
      this.seqHi > MAX_HI ||
      (this.seqHi === MAX_HI && this.seqLo >= MAX_LO)
    ) {
      this.setPre();
      this.initSeqAndInc();
    }
    this.fillSeq();
    const b = this.buf;
    return String.fromCharCode(
      b[0],
      b[1],
      b[2],
      b[3],
      b[4],
      b[5],
      b[6],
      b[7],
      b[8],
      b[9],
      b[10],
      b[11],
      b[12],
      b[13],
      b[14],
      b[15],
      b[16],
      b[17],
      b[18],
      b[19],
      b[20],
      b[21],
    );
  }

  /**
   * Resets the prefix and counter for the nuid. This is typically
   * called automatically from within next() if the current sequence
   * exceeds the resolution of the nuid.
   */
  reset() {
    this.init();
  }
}

// 62^8 = 218,340,105,584,896 — fits safely in Number.MAX_SAFE_INTEGER (2^53-1).
const TOKEN_SPACE = 218340105584896;

/**
 * Returns an 8-char base62 token from `Math.random()`. Intended for use as
 * the per-request suffix on a shared `_INBOX.<nuid>.*` mux subscription —
 * mirrors the `replySuffixLen=8` token generated by nats.go in
 * `(nc *Conn).newRespInbox`.
 *
 * Not cryptographically random and does not check for collisions. Collision
 * avoidance relies on (a) the per-connection nuid prefix isolating namespace
 * across connections, and (b) the in-flight token set being small relative
 * to the 62^8 ≈ 2.18e14 space.
 */
export function randomToken(): string {
  let n = Math.floor(Math.random() * TOKEN_SPACE);
  let d = n % base;
  const c0 = DIGIT_CODES[d];
  n = (n - d) / base;
  d = n % base;
  const c1 = DIGIT_CODES[d];
  n = (n - d) / base;
  d = n % base;
  const c2 = DIGIT_CODES[d];
  n = (n - d) / base;
  d = n % base;
  const c3 = DIGIT_CODES[d];
  n = (n - d) / base;
  d = n % base;
  const c4 = DIGIT_CODES[d];
  n = (n - d) / base;
  d = n % base;
  const c5 = DIGIT_CODES[d];
  n = (n - d) / base;
  d = n % base;
  const c6 = DIGIT_CODES[d];
  n = (n - d) / base;
  const c7 = DIGIT_CODES[n];
  return String.fromCharCode(c0, c1, c2, c3, c4, c5, c6, c7);
}

/**
 * A nuid instance you can use by simply calling `next()` on it.
 */
export const nuid: Nuid = new Nuid();
