name: test cjs

on:
  push:
    tags:
      - "*"
    branches:
      - "*"
  pull_request:
    branches: [main]

jobs:
  test:
    strategy:
      matrix:
        node-version: [22.x]
        deno-version: [2.1.x]

    runs-on: ubuntu-latest

    steps:
      - name: Checkout nuid
        uses: actions/checkout@v3
        with:
          fetch-depth: 1
      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v3
        with:
          node-version: ${{ matrix.node-version }}
      - name: Use Deno Version ${{ matrix.deno-version }}
        uses: denoland/setup-deno@v1
        with:
          deno-version: ${{ matrix.deno-version }}
      - name: lint
        run: |
          deno fmt --check src/ test/
          deno lint

      - name: test
        env:
          TMPDIR: ${{ runner.temp }}
          CI: true
        run: |
          npm ci
          npm run prepack
          npm test
