name: NUID NPM release

on:
  release:
    types: [created]

jobs:
  npm_publish:
    strategy:
      matrix:
        node-version: [25.x]
        deno-version: [2.7.x]

    runs-on: ubuntu-latest
    permissions:
      contents: read
      id-token: write

    steps:
      - name: Checkout nuid
        uses: actions/checkout@v6
        with:
          fetch-depth: 1
      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v6
        with:
          node-version: ${{ matrix.node-version }}
          registry-url: "https://registry.npmjs.org"
          cache: "npm"
      - name: Use Deno Version ${{ matrix.deno-version }}
        uses: denoland/setup-deno@v2
        with:
          deno-version: ${{ matrix.deno-version }}
      - run: npm install -g npm
      - run: npm ci
      - name: Set tag
        run: |
          VER="${GITHUB_REF#refs/*/}"
          if [[ "$VER" == *-* ]]; then
            echo "NPM_TAG=next" >> $GITHUB_ENV
          else
            echo "NPM_TAG=latest" >> $GITHUB_ENV
          fi
      - run: npm test
      - run: npm publish --provenance --access public --tag=${NPM_TAG}
      - name: Publish JSR (skip on pre-release)
        if: env.NPM_TAG == 'latest'
        run: npx jsr publish --allow-dirty
